# Generated by Django 5.2.15 on 2026-06-15 11:41

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("broker_name", models.CharField(default="MT5", max_length=64)),
                ("account_number", models.CharField(blank=True, max_length=64)),
                ("server", models.CharField(blank=True, max_length=128)),
                ("currency", models.CharField(blank=True, max_length=16)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "equity",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "margin",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "free_margin",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "leverage",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("trade_allowed", models.BooleanField(default=False)),
                ("connected", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Demo paper account", max_length=128)),
                (
                    "starting_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("10000"), max_digits=20),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("10000"), max_digits=20),
                ),
                (
                    "equity",
                    models.DecimalField(decimal_places=2, default=Decimal("10000"), max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_risk_per_trade_percentage",
                    models.DecimalField(decimal_places=4, default=Decimal("1.0"), max_digits=7),
                ),
                (
                    "max_daily_loss_percentage",
                    models.DecimalField(decimal_places=4, default=Decimal("3.0"), max_digits=7),
                ),
                (
                    "max_weekly_loss_percentage",
                    models.DecimalField(decimal_places=4, default=Decimal("7.0"), max_digits=7),
                ),
                ("max_open_positions", models.PositiveIntegerField(default=3)),
                ("max_positions_per_symbol", models.PositiveIntegerField(default=1)),
                (
                    "max_leverage",
                    models.DecimalField(decimal_places=2, default=Decimal("30"), max_digits=10),
                ),
                (
                    "max_lot_size",
                    models.DecimalField(decimal_places=6, default=Decimal("1.0"), max_digits=18),
                ),
                (
                    "min_stop_loss_points",
                    models.DecimalField(decimal_places=4, default=Decimal("50"), max_digits=18),
                ),
                (
                    "max_stop_loss_points",
                    models.DecimalField(decimal_places=4, default=Decimal("2000"), max_digits=18),
                ),
                (
                    "max_spread_points",
                    models.DecimalField(decimal_places=4, default=Decimal("30"), max_digits=18),
                ),
                (
                    "max_slippage_points",
                    models.DecimalField(decimal_places=4, default=Decimal("20"), max_digits=18),
                ),
                ("stop_trading_after_losses", models.PositiveIntegerField(default=3)),
                ("stale_data_threshold_seconds", models.PositiveIntegerField(default=10)),
                (
                    "max_price_jump_percentage",
                    models.DecimalField(decimal_places=4, default=Decimal("1.0"), max_digits=7),
                ),
                ("require_stop_loss", models.BooleanField(default=True)),
                ("require_take_profit", models.BooleanField(default=False)),
                ("trading_start_time", models.TimeField(blank=True, null=True)),
                ("trading_end_time", models.TimeField(blank=True, null=True)),
                ("allowed_symbols", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("strategy_type", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("is_live_enabled", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="trading_eng_slug_e36b2d_idx"),
                    models.Index(
                        fields=["is_active", "is_live_enabled"],
                        name="trading_eng_is_acti_2bbd8b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("timeframe", models.CharField(default="M5", max_length=16)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("HOLD", "Hold")], max_length=8
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("BACKTEST", "Backtest"), ("PAPER", "Paper"), ("LIVE", "Live")],
                        default="PAPER",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trading_engine.strategy"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LivePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("broker_position_id", models.CharField(max_length=128, unique=True)),
                (
                    "side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8),
                ),
                ("volume", models.DecimalField(decimal_places=6, max_digits=18)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("current_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "stop_loss",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "take_profit",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "swap",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                ("status", models.CharField(default="OPEN", max_length=32)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broker_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading_engine.brokeraccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.strategy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("broker_order_id", models.CharField(blank=True, max_length=128)),
                ("broker_deal_id", models.CharField(blank=True, max_length=128)),
                (
                    "side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8),
                ),
                ("order_type", models.CharField(default="MARKET", max_length=32)),
                ("requested_volume", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "filled_volume",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=18),
                ),
                (
                    "requested_price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "filled_price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "stop_loss",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "take_profit",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("deviation_points", models.PositiveIntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PRE_CHECKED", "Pre-checked"),
                            ("SENT", "Sent"),
                            ("FILLED", "Filled"),
                            ("PARTIALLY_FILLED", "Partially filled"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=32,
                    ),
                ),
                ("broker_retcode", models.CharField(blank=True, max_length=64)),
                ("broker_comment", models.TextField(blank=True)),
                ("raw_request_json", models.JSONField(blank=True, default=dict)),
                ("raw_response_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broker_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading_engine.brokeraccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.signal",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.strategy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("initial_balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("final_balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_return", models.DecimalField(decimal_places=4, max_digits=12)),
                ("max_drawdown", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12),
                ),
                (
                    "profit_factor",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12),
                ),
                ("total_trades", models.PositiveIntegerField(default=0)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("metrics_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.strategy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrategyParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=255)),
                ("value_type", models.CharField(default="str", max_length=32)),
                ("description", models.TextField(blank=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="trading_engine.strategy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("market_type", models.CharField(default="forex", max_length=32)),
                ("broker_symbol", models.CharField(max_length=64)),
                ("timeframe", models.CharField(default="M5", max_length=16)),
                (
                    "min_lot",
                    models.DecimalField(decimal_places=6, default=Decimal("0.01"), max_digits=18),
                ),
                (
                    "max_lot",
                    models.DecimalField(decimal_places=6, default=Decimal("100"), max_digits=18),
                ),
                (
                    "lot_step",
                    models.DecimalField(decimal_places=6, default=Decimal("0.01"), max_digits=18),
                ),
                (
                    "point",
                    models.DecimalField(decimal_places=8, default=Decimal("0.0001"), max_digits=18),
                ),
                ("digits", models.PositiveSmallIntegerField(default=5)),
                (
                    "spread_limit_points",
                    models.DecimalField(decimal_places=4, default=Decimal("30"), max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_live_enabled", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["symbol"], name="trading_eng_symbol_c53cf0_idx"),
                    models.Index(
                        fields=["is_active", "is_live_enabled"],
                        name="trading_eng_is_acti_2a502a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("BACKTEST", "Backtest"), ("PAPER", "Paper"), ("LIVE", "Live")],
                        default="PAPER",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("emotions", models.TextField(blank=True)),
                ("mistakes", models.TextField(blank=True)),
                ("lessons", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.liveorder",
                    ),
                ),
                (
                    "related_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.liveposition",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="signal",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trading_engine.tradingsymbol"
            ),
        ),
        migrations.CreateModel(
            name="RiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("severity", models.CharField(default="WARNING", max_length=32)),
                ("decision", models.CharField(default="BLOCKED", max_length=32)),
                ("triggered_rules", models.JSONField(blank=True, default=list)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.strategy",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("current_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "stop_loss",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "take_profit",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="OPEN", max_length=32)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading_engine.paperaccount",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8),
                ),
                ("order_type", models.CharField(default="MARKET", max_length=32)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "requested_price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "filled_price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PRE_CHECKED", "Pre-checked"),
                            ("SENT", "Sent"),
                            ("FILLED", "Filled"),
                            ("PARTIALLY_FILLED", "Partially filled"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=32,
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "take_profit",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading_engine.paperaccount",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketDataHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("latest_tick_at", models.DateTimeField(blank=True, null=True)),
                ("latest_candle_at", models.DateTimeField(blank=True, null=True)),
                ("tick_age_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("candle_age_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("is_fresh", models.BooleanField(default=False)),
                (
                    "spread_points",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("broker_time", models.DateTimeField()),
                ("local_time", models.DateTimeField()),
                ("bid", models.DecimalField(decimal_places=8, max_digits=20)),
                ("ask", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "last",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
                ),
                ("spread_points", models.DecimalField(decimal_places=4, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="liveposition",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="trading_engine.tradingsymbol"
            ),
        ),
        migrations.AddField(
            model_name="liveorder",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="trading_engine.tradingsymbol"
            ),
        ),
        migrations.CreateModel(
            name="LiveCandleSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timeframe", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candles_created", models.PositiveIntegerField(default=0)),
                ("candles_updated", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="STARTED", max_length=32)),
                ("message", models.TextField(blank=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "volume",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
                ),
                ("timeframe", models.CharField(default="M5", max_length=16)),
                ("source", models.CharField(default="manual", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candles",
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("BACKTEST", "Backtest"), ("PAPER", "Paper"), ("LIVE", "Live")],
                        default="PAPER",
                        max_length=16,
                    ),
                ),
                ("is_running", models.BooleanField(default=False)),
                ("live_trading_armed", models.BooleanField(default=False)),
                ("kill_switch_active", models.BooleanField(default=False)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "active_strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.strategy",
                    ),
                ),
                (
                    "active_symbol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BacktestTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "exit_price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8),
                ),
                ("pnl", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20)),
                (
                    "pnl_percentage",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12),
                ),
                ("exit_reason", models.CharField(blank=True, max_length=128)),
                (
                    "backtest_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="trading_engine.backtestrun",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading_engine.tradingsymbol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="trading_engine.tradingsymbol"
            ),
        ),
        migrations.CreateModel(
            name="AIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_type", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "report_type", "-created_at"],
                        name="trading_eng_user_id_4d326b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                ("severity", models.CharField(default="INFO", max_length=32)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action", "severity", "-created_at"],
                        name="trading_eng_action_4258fa_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="brokeraccount",
            index=models.Index(
                fields=["user", "broker_name", "account_number"],
                name="trading_eng_user_id_5ab844_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paperaccount",
            index=models.Index(fields=["user", "is_active"], name="trading_eng_user_id_4de42e_idx"),
        ),
        migrations.AddIndex(
            model_name="risksettings",
            index=models.Index(fields=["user"], name="trading_eng_user_id_820c6d_idx"),
        ),
        migrations.AddIndex(
            model_name="strategyparameter",
            index=models.Index(fields=["strategy", "name"], name="trading_eng_strateg_fd253d_idx"),
        ),
        migrations.AddConstraint(
            model_name="strategyparameter",
            constraint=models.UniqueConstraint(
                fields=("strategy", "name"), name="uniq_strategy_parameter"
            ),
        ),
        migrations.AddIndex(
            model_name="tradejournalentry",
            index=models.Index(
                fields=["user", "mode", "-created_at"], name="trading_eng_user_id_17764d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["symbol", "strategy", "-timestamp"], name="trading_eng_symbol__71e7ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(fields=["mode", "-created_at"], name="trading_eng_mode_ee2255_idx"),
        ),
        migrations.AddConstraint(
            model_name="signal",
            constraint=models.UniqueConstraint(
                fields=("strategy", "symbol", "timeframe", "timestamp", "signal_type", "mode"),
                name="uniq_signal_deduplication_key",
            ),
        ),
        migrations.AddIndex(
            model_name="riskevent",
            index=models.Index(
                fields=["event_type", "decision", "-created_at"],
                name="trading_eng_event_t_6f5dd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["account", "status", "symbol"], name="trading_eng_account_f86733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperorder",
            index=models.Index(
                fields=["account", "status", "-created_at"], name="trading_eng_account_901b92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketdatahealthcheck",
            index=models.Index(
                fields=["symbol", "-checked_at", "is_fresh"], name="trading_eng_symbol__4e06c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livetick",
            index=models.Index(
                fields=["symbol", "-broker_time"], name="trading_eng_symbol__4f4085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livetick",
            index=models.Index(fields=["created_at"], name="trading_eng_created_ab7b31_idx"),
        ),
        migrations.AddIndex(
            model_name="liveposition",
            index=models.Index(
                fields=["user", "status", "symbol"], name="trading_eng_user_id_c5d3cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liveposition",
            index=models.Index(
                fields=["broker_position_id"], name="trading_eng_broker__1e21cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liveorder",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="trading_eng_user_id_29a2ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liveorder",
            index=models.Index(
                fields=["symbol", "side", "-created_at"], name="trading_eng_symbol__40f614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liveorder",
            index=models.Index(fields=["broker_order_id"], name="trading_eng_broker__508ed9_idx"),
        ),
        migrations.AddIndex(
            model_name="livecandlesynclog",
            index=models.Index(
                fields=["symbol", "timeframe", "-started_at"], name="trading_eng_symbol__3854d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candle",
            index=models.Index(
                fields=["symbol", "timeframe", "timestamp"], name="trading_eng_symbol__efb664_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candle",
            index=models.Index(
                fields=["source", "created_at"], name="trading_eng_source_c57377_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.UniqueConstraint(
                fields=("symbol", "timestamp", "timeframe", "source"),
                name="uniq_candle_symbol_timeframe_source",
            ),
        ),
        migrations.AddIndex(
            model_name="botstate",
            index=models.Index(
                fields=["user", "mode", "is_running", "kill_switch_active"],
                name="trading_eng_user_id_e199b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backtesttrade",
            index=models.Index(
                fields=["backtest_run", "symbol"], name="trading_eng_backtes_ea5934_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["symbol", "strategy", "-created_at"], name="trading_eng_symbol__481e61_idx"
            ),
        ),
    ]
